<?php
/**
 * Created by PhpStorm.
 * User: zaiki
 * Date: 21.11.2018
 * Time: 23:20
 */

namespace app\models;


use Yii;
use yii\base\Model;

class SendEmailForm extends Model
{
    public $email;

    public function rules()
    {
        return [
            ['email', 'filter', 'filter' => 'trim'],        //убираем пробелы по краям
            ['email', 'required'],
            ['email', 'email'],
            ['email', 'exist',
                'targetClass' => User::className(),
                'filter' => [
                    'status' => User::STATUS_ACTIVE
                ],
                'message' => 'Данный email не зарегистрирован'
            ],
        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'email' => 'Электронная почта',
        ];
    }

    /*Метод, находит активированного пользователя с введенным мэйлом, записывать секретный ключ
    и отправлять ему письмо с ссылкой для смены пароля*/
    public function sendEmail()
    {
        /* @var $user User */
        $user = User::findOne([
            'status' => User::STATUS_ACTIVE,
            'email' => $this->email
        ]);
        if ($user) {
            $user->generateSecretKey();     //
            if ($user->save()) {
                //Отправка письма
                return Yii::$app->mailer->compose('resetPassword', ['user' => $user])
                    ->setFrom([Yii::$app->params['supportEmail'] => Yii::$app->name . '(Отправленно роботом)'])//от кого отпр
                    ->setTo($this->email)//Отправить кому
                    ->setSubject('Сброс пароля для' . Yii::$app->name)//тема письма
                    ->send();
            }
        }
        return false;
    }
}